version: '3.8'
services:
  backend:
    image: akshata14/backend:latest
    container_name: django_api
    environment:
      - ALLOWED_HOSTS=*

  frontend:
    image: akshata14/frontend:latest
    container_name: react_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
